{
 "title": "Hayrat_Data_Center_Monitoring_V1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Cabinet",
    "label": "Cabinet",
    "query": "SELECT Hall_1,FrontDoor FROM DC_Istanbul_Cabinet WHERE time > now() - 10m"
   },
   {
    "name": "Hall",
    "label": "Hall",
    "query": "SELECT Zone_1,PIRsensor1 FROM DC_Istanbul_Hall WHERE time > now() - 10m"
   }
  ]
 },
 "panels": [
  { "title": "$Hall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Hall" },
  {
   "title": "PIR-1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "PIRsensor1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "PIR-2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "PIRsensor2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "PIR-3",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "PIRsensor3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "PIR-4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "LightSensor4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "PIR-5",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "PIRsensor5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "PIR-6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "PIRsensor6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Light-1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "LightSensor1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Light-2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "LightSensor2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Light-3",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "LightSensor3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Light-4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "LightSensor4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Light-5",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "LightSensor5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Light-6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "LightSensor6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Voice-1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "VoiceSensor1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Voice-2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "VoiceSensor2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Voice-3",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "VoiceSensor3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Voice-4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "VoiceSensor4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Voice-5",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "VoiceSensor5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Voice-6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "VoiceSensor6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Water-1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "WaterSensor1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Water-2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "WaterSensor2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Water-3",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "WaterSensor3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Water-4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "WaterSensor4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Water-5",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "WaterSensor5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  {
   "title": "Water-6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Hall",
     "select": [
      [
       { "params": [ "WaterSensor6" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Zone_1", "operator": "=~", "value": "/^$Hall$/" }
     ]
    }
   ]
  },
  { "title": "$Cabinet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "Cabinet" },
  {
   "title": "Front Door",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "FrontDoor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    }
   ]
  },
  {
   "title": "Front Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "FrontTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    }
   ]
  },
  {
   "title": "Front Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "FrontHumidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    }
   ]
  },
  {
   "title": "Front Dew",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "FrontDewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    }
   ]
  },
  {
   "title": "Rear Temp",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "RearTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    }
   ]
  },
  {
   "title": "Rear Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "RearHumidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    }
   ]
  },
  {
   "title": "Rear Dew",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "RearDewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    }
   ]
  },
  {
   "title": "Alert List",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "RearDewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "FrontDewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    }
   ]
  },
  {
   "title": "Rear Door",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "RearDoor" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature Time Line",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "query": "SELECT mean(\"FrontTemperature\") FROM \"DC_Istanbul_Cabinet\" WHERE (\"Hall_1\" = 'Cabinet_1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "FrontTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "RearTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity Time Line",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "FrontHumidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "RearHumidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    }
   ]
  },
  {
   "title": "DewPoint Time Line",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "FrontDewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DC_Istanbul_Cabinet",
     "select": [
      [
       { "params": [ "RearDewpoint" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "Hall_1", "operator": "=~", "value": "/^$Cabinet$/" }
     ]
    }
   ]
  }
 ]
}